# backend/performance_analyzer.py
# ──────────────────────────────────────────────────────────────────────────────
# Performance Analysis Module — COA CPU Simulator
#
# DESIGN PRINCIPLE: This module is completely independent of the CPU simulation
# engine. It takes the already-produced `trace` list (generated by cpu_engine.py)
# and derives performance metrics from it. The simulation logic is NEVER modified.
#
# Consumed trace entry fields:
#   clock      : int  — global clock cycle number (1-based)
#   instr_num  : int  — which instruction this micro-op belongs to (1-based)
#   phase      : str  — "FETCH" | "DECODE" | "DECODE (Indirect)" | "EXECUTE"
#   t_label    : str  — "T0" | "T1" | ... (micro-op timing label)
#   rtl        : str  — RTL expression string
# ──────────────────────────────────────────────────────────────────────────────


def compute(trace: list) -> dict:
    """
    Compute all performance metrics from a simulation trace.

    Parameters
    ----------
    trace : list of clock-cycle dicts produced by CPU._push()

    Returns
    -------
    dict with keys:
        total_instructions  : int
        total_cycles        : int
        cpi                 : float  (0.0 if no instructions)
        throughput          : float  (0.0 if no cycles)
        cycle_breakdown     : dict   — counts per pipeline stage
        instruction_details : list   — per-instruction summary (for line chart)
    """
    if not trace:
        return _empty_metrics()

    # ── 1. Basic totals ────────────────────────────────────────────────────────
    total_cycles      = trace[-1]["clock"]          # last clock value = total cycles
    total_instructions = trace[-1]["instr_num"]     # last instr_num = total instructions

    # ── 2. CPI / Throughput ───────────────────────────────────────────────────
    cpi        = round(total_cycles / total_instructions, 4) if total_instructions else 0.0
    throughput = round(total_instructions / total_cycles, 4) if total_cycles      else 0.0

    # ── 3. Cycle breakdown by pipeline stage ──────────────────────────────────
    # Each entry in trace represents one clock pulse; we classify it by phase.
    breakdown = {"fetch": 0, "decode": 0, "execute": 0}
    for entry in trace:
        phase = entry.get("phase", "").upper()
        if phase.startswith("FETCH"):
            breakdown["fetch"] += 1
        elif phase.startswith("DECODE"):
            breakdown["decode"] += 1
        elif phase.startswith("EXECUTE"):
            breakdown["execute"] += 1
        # Unknown phases (shouldn't occur) are ignored to stay forward-compatible

    # ── 4. Per-instruction details (for line chart + per-bar data) ────────────
    # Walk the trace and group micro-ops by instr_num.
    # Each instruction spans a contiguous run of clock cycles.
    instr_map = {}   # instr_num → {start, end, fetch_c, decode_c, execute_c, rtl_summary}
    for entry in trace:
        n     = entry["instr_num"]
        clk   = entry["clock"]
        phase = entry.get("phase", "").upper()

        if n not in instr_map:
            instr_map[n] = {
                "instr_num" : n,
                "start_cycle": clk,
                "end_cycle"  : clk,
                "total_cycles": 0,
                "fetch_cycles"  : 0,
                "decode_cycles" : 0,
                "execute_cycles": 0,
                # Capture first RTL seen (T0 → usually "AR ← PC")
                "rtl_example": entry.get("rtl", ""),
            }

        rec = instr_map[n]
        rec["end_cycle"] = max(rec["end_cycle"], clk)

        # Stage cycle counts per instruction
        if phase.startswith("FETCH"):
            rec["fetch_cycles"] += 1
        elif phase.startswith("DECODE"):
            rec["decode_cycles"] += 1
        elif phase.startswith("EXECUTE"):
            rec["execute_cycles"] += 1

    # Convert to sorted list and compute total cycles per instruction
    instruction_details = []
    for n in sorted(instr_map.keys()):
        rec = instr_map[n]
        rec["total_cycles"] = (
            rec["fetch_cycles"] + rec["decode_cycles"] + rec["execute_cycles"]
        )
        instruction_details.append(rec)

    # ── 5. Assemble % breakdown for pie chart ─────────────────────────────────
    total_classified = breakdown["fetch"] + breakdown["decode"] + breakdown["execute"]
    def pct(count):
        return round(count / total_classified * 100, 1) if total_classified else 0.0

    cycle_breakdown_pct = {
        "fetch"  : pct(breakdown["fetch"]),
        "decode" : pct(breakdown["decode"]),
        "execute": pct(breakdown["execute"]),
    }

    return {
        # ── Top-level metrics ──
        "total_instructions" : total_instructions,
        "total_cycles"       : total_cycles,
        "cpi"                : cpi,
        "throughput"         : throughput,

        # ── Stage breakdown (raw counts) ──
        "cycle_breakdown"    : breakdown,

        # ── Stage breakdown (percentages for pie chart) ──
        "cycle_breakdown_pct": cycle_breakdown_pct,

        # ── Per-instruction detail list (for line + bar charts) ──
        "instruction_details": instruction_details,
    }


def _empty_metrics() -> dict:
    """Return zeroed metrics when there is no trace (e.g. div-by-zero guard)."""
    return {
        "total_instructions" : 0,
        "total_cycles"       : 0,
        "cpi"                : 0.0,
        "throughput"         : 0.0,
        "cycle_breakdown"    : {"fetch": 0, "decode": 0, "execute": 0},
        "cycle_breakdown_pct": {"fetch": 0.0, "decode": 0.0, "execute": 0.0},
        "instruction_details": [],
    }
